package com.example.seedstockkeeper6.ui.theme
import androidx.compose.ui.graphics.Color

// ---------- Tanesuke Light Theme ----------
val primaryTanesukeLight = Color(0xFF646115)
val onPrimaryTanesukeLight = Color(0xFFFFFFFF)
val primaryContainerTanesukeLight = Color(0xFFECE68D)
val onPrimaryContainerTanesukeLight = Color(0xFF4C4900)
val secondaryTanesukeLight = Color(0xFF625F42)
val onSecondaryTanesukeLight = Color(0xFFFFFFFF)
val secondaryContainerTanesukeLight = Color(0xFFE8E4BE)
val onSecondaryContainerTanesukeLight = Color(0xFF4A482C)
val tertiaryTanesukeLight = Color(0xFF3F6655)
val onTertiaryTanesukeLight = Color(0xFFFFFFFF)
val tertiaryContainerTanesukeLight = Color(0xFFC1ECD6)
val onTertiaryContainerTanesukeLight = Color(0xFF274E3E)
val errorTanesukeLight = Color(0xFFBA1A1A)
val onErrorTanesukeLight = Color(0xFFFFFFFF)
val errorContainerTanesukeLight = Color(0xFFFFDAD6)
val onErrorContainerTanesukeLight = Color(0xFF93000A)
val backgroundTanesukeLight = Color(0xFFFEF9EB)
val onBackgroundTanesukeLight = Color(0xFF1D1C14)
val surfaceTanesukeLight = Color(0xFFFEF9EB)
val onSurfaceTanesukeLight = Color(0xFF1D1C14)
val surfaceVariantTanesukeLight = Color(0xFFE7E3D1)
val onSurfaceVariantTanesukeLight = Color(0xFF49473A)
val outlineTanesukeLight = Color(0xFF7A7768)
val outlineVariantTanesukeLight = Color(0xFFCAC7B5)
val scrimTanesukeLight = Color(0xFF000000)
val inverseSurfaceTanesukeLight = Color(0xFF323128)
val inverseOnSurfaceTanesukeLight = Color(0xFFF5F1E3)
val inversePrimaryTanesukeLight = Color(0xFFCFCA74)
val surfaceDimTanesukeLight = Color(0xFFDEDACD)
val surfaceBrightTanesukeLight = Color(0xFFFEF9EB)
val surfaceContainerLowestTanesukeLight = Color(0xFFFFFFFF)
val surfaceContainerLowTanesukeLight = Color(0xFFF8F3E6)
val surfaceContainerTanesukeLight = Color(0xFFF2EEE0)
val surfaceContainerHighTanesukeLight = Color(0xFFECE8DB)
val surfaceContainerHighestTanesukeLight = Color(0xFFE6E2D5)

// ---------- Tanesuke Dark Theme ----------
val primaryTanesukeDark = Color(0xFFCFCA74)
val onPrimaryTanesukeDark = Color(0xFF343200)
val primaryContainerTanesukeDark = Color(0xFF4C4900)
val onPrimaryContainerTanesukeDark = Color(0xFFECE68D)
val secondaryTanesukeDark = Color(0xFFCCC8A4)
val onSecondaryTanesukeDark = Color(0xFF333118)
val secondaryContainerTanesukeDark = Color(0xFF4A482C)
val onSecondaryContainerTanesukeDark = Color(0xFFE8E4BE)
val tertiaryTanesukeDark = Color(0xFFA5D0BA)
val onTertiaryTanesukeDark = Color(0xFF0D3728)
val tertiaryContainerTanesukeDark = Color(0xFF274E3E)
val onTertiaryContainerTanesukeDark = Color(0xFFC1ECD6)
val errorTanesukeDark = Color(0xFFFFB4AB)
val onErrorTanesukeDark = Color(0xFF690005)
val errorContainerTanesukeDark = Color(0xFF93000A)
val onErrorContainerTanesukeDark = Color(0xFFFFDAD6)
val backgroundTanesukeDark = Color(0xFF14140C)
val onBackgroundTanesukeDark = Color(0xFFE6E2D5)
val surfaceTanesukeDark = Color(0xFF14140C)
val onSurfaceTanesukeDark = Color(0xFFE6E2D5)
val surfaceVariantTanesukeDark = Color(0xFF49473A)
val onSurfaceVariantTanesukeDark = Color(0xFFCAC7B5)
val outlineTanesukeDark = Color(0xFF949181)
val outlineVariantTanesukeDark = Color(0xFF49473A)
val scrimTanesukeDark = Color(0xFF000000)
val inverseSurfaceTanesukeDark = Color(0xFFE6E2D5)
val inverseOnSurfaceTanesukeDark = Color(0xFF323128)
val inversePrimaryTanesukeDark = Color(0xFF646115)
val surfaceDimTanesukeDark = Color(0xFF14140C)
val surfaceBrightTanesukeDark = Color(0xFF3B3930)
val surfaceContainerLowestTanesukeDark = Color(0xFF0F0E07)
val surfaceContainerLowTanesukeDark = Color(0xFF1D1C14)
val surfaceContainerTanesukeDark = Color(0xFF212018)
val surfaceContainerHighTanesukeDark = Color(0xFF2B2A21)
val surfaceContainerHighestTanesukeDark = Color(0xFF36352C)


